- apps/web/src/components/WelcomeHeader.tsx
- apps/web/src/pages/index.tsx
> feature(ui-ux): added welcome screen

- .github/CODEOWNERS
> chore(workflow): added code owners for src dir

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/WalletAddressInput.tsx
- apps/web/src/components/commons/ActionButton.tsx
- apps/web/src/styles/globals.scss
- apps/web/src/types.ts
- Modify current action button and move to a common component
Fixes #
> feature(ui-ux): add common cta button

- apps/web/src/components/EnvironmentNetworkSwitch.tsx
- apps/web/src/components/WalletAddressInput.tsx
- apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
- apps/web/src/types.ts
- Add "Local" environment network option for dev/test node env. Will be used mostly for e2e testing
Fixes #
> feature(ui-ux): add local enviroment option on dev mode

- .github/labels.yml
Adds 2 new labels for `contract` and `server` to better distinguish issues.
Have left the rest as-is, although we should probably re-look them since some of them do not look necessary.
> chore(workflow): Add contract and server area label

- .github/CODEOWNERS
- apps/web/package.json
- apps/web/src/layouts/Base.tsx
- pnpm-lock.yaml
Bumping wagmi to 0.9 (latest supported by connectkit) - https://wagmi.sh/react/migration-guide#09x-breaking-changes
Fixes #
> chore(deps): bump wagmi and connectkit

- apps/server/package.json
- apps/server/src/AppModule.ts
- pnpm-lock.yaml
In this PR to prevent spamming and to ensure our endpoints are protected, we have added rate limiting on our endpoints.
This will ensure API requests made by a throttled user or app will fail after reaching its limit 
Fixes #199
Default rate limiting is 10 requests from the same IP can be made to a single endpoint in 1 minute. This will get reset after 1 min interval.
Decoraters
1. API specific custom rate limiting 
we can use ```@Throttle(limit: number = 30, ttl: number = 60)```  to define api specific rate limiting  
2. Skip rate limiting
To skip the rate limiting for specific api we can use  ```@SkipThrottle(skip = true)```
This decorator can be used to skip a route or a class or to negate the skipping of a route in a class that is skipped.
```
@SkipThrottle()
@Controller()
export …
```
> feature(api): setup api rate limiter to avoid spamming

- README.md
- packages/smartcontracts/package.json
- packages/smartcontracts/src/.env.example
- packages/smartcontracts/src/hardhat.config.ts
- packages/smartcontracts/src/scripts/deployBridgeImplementation.ts
- packages/smartcontracts/src/scripts/deployBridgeProxy.ts
- packages/smartcontracts/src/scripts/deployERC20.ts
- pnpm-lock.yaml
This PR introduces the deployment script for the Bridge and test tokens smart contracts
Fixes #
> feat(SmartContracts): Deployment script for Goerli test net

- packages/smartcontracts/src/contracts/BridgeV1.sol
- packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.supportedToken.spec.ts
- packages/smartcontracts/src/tests/testUtils/mathUtils.ts
Cleaner helper functions with interface.
Switched to calldata when using bytes and strings.
Fixes #157 
Fixes #226
> feat(Contracts): cleaner helper functions and switch to calldata

- README.md
- packages/smartcontracts/src/scripts/mintTestToken.ts
As the title states, on running this script user will be able to mint `100,000` test tokens on testnet.
Fixes #
> chore(Contracts): Added script for minting and approving test tokens on Goerli testnet

- apps/web/package.json
- apps/web/src/layouts/Base.tsx
- pnpm-lock.yaml
Current production build for web is failing, this can also be seen on the deployment preview of open PRs.
Issue is related with the latest version of connectkit@`1.1.2`
Ticket related to this issue has been raised: https://github.com/family/connectkit/issues/89
Fixes #
> fix(build): fix issue on web build

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/layouts/Base.tsx
- apps/web/src/layouts/contexts/NetworkContext.tsx
- apps/web/src/types.ts
- Display balance per token instead of the overall balance
- Add type safety
Fixes #
> feat(core): display token balance instead of overall balance

- README.md
- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/ConfirmTransferModal.tsx
Update contract address to always use deployed bridge proxy address, should never send to 0x0 address.
Thanks for catching this @weiyuan95!
Fixes #
> fix(ui-ux): always use bridge proxy contract address to write

- apps/server/src/AppConfig.ts
- apps/server/src/AppController.ts
- apps/server/src/AppService.ts
- apps/server/test-i9n/BridgeApp.i9n.ts
- apps/server/test-i9n/defichain/stats.i9n.ts
- apps/server/test-i9n/defichain/wallet.i9n.ts
The getAllEventsFromBlockNumber function returns an array of confirmed BRIDGE_TO_DEFI_CHAIN events from a given block number. It will be used for the backend server to bridge EVM tokens to DFC.
Fixes #183
It is a POST request that takes in blockNumber & contractAddress as body params.
> feat(EVMTransactionConfirmer): Build getAllEventsFromBlockNumber function and integration tests

- apps/server/src/defichain/model/NetworkDto.ts
- apps/server/src/defichain/services/WhaleWalletService.ts
- apps/server/src/prisma/migrations/20230201114008_init/migration.sql
- apps/server/src/prisma/schema.prisma
- apps/web/src/components/EnvironmentNetworkSwitch.tsx
- apps/web/src/components/WalletAddressInput.tsx
- apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
- apps/web/src/layouts/Base.tsx
- apps/web/src/layouts/contexts/ContractContext.tsx
- apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
- apps/web/src/store/website.tsx
- apps/web/src/types.ts
> fix(ui-ux): fixed network env issue and network based address indexing

- README.md
- packages/smartcontracts/src/contracts/BridgeV1.sol
- packages/smartcontracts/src/hardhat.config.ts
As per the title, Added sections for sending and removing funds on bridge contract. 
There is also an guide on how to add owners to gnosis safe .
Also, indexed the events fields. Upto 3 fields can be indexed per event. 
Indexed fields are easy to find by off chain tools. 
Fixes #
> docs(ReadMe): Updated readMe & indexed fields on events.

- .github/renovate.json
- apps/server/src/AppConfig.ts
- apps/server/src/AppService.ts
- apps/server/src/modules/EthersModule.ts
- apps/server/test-i9n/BridgeApp.i9n.ts
- apps/server/test-i9n/defichain/stats.i9n.ts
- apps/server/test-i9n/defichain/wallet.i9n.ts
- apps/server/test-i9n/testing/BridgeContractFixture.i9n.ts
- apps/server/test-i9n/testing/BridgeContractFixture.ts
- apps/server/test-i9n/testing/BridgeServerTestingApp.ts
- apps/server/test-i9n/testing/TestingModule.ts
- docker-compose.yml
- package.json
- packages/smartcontracts/package.json
- packages/smartcontracts/src/tests/testUtils/mathUtils.ts
- turbo.json
- Lots of test code cleanup. The changes here should make writing additional tests a lot easier and cleaner
- Test fixtures
- Config cleanup
- Some formatting changes, realised that the `lint` command was not set correctly
Fixes #
> chore(testing): Bridge contracts related test fixtures for DRY-ness

- .github/renovate.json
- apps/server/test-i9n/defichain/DeFiChainStubContainer.ts
- apps/server/test-i9n/defichain/address.i9n.ts
- apps/server/test-i9n/defichain/send.i9n.ts
- apps/server/test-i9n/defichain/stats.i9n.ts
- pnpm-lock.yaml
> chore(tests): update renovate logic and moved out timeouts

- apps/server/.env
- apps/server/src/AppConfig.ts
- apps/server/src/AppService.ts
- apps/server/src/modules/EthersModule.ts
- apps/server/test-i9n/testing/TestingModule.ts
As per title. Consolidates configs, whether or not the app is ran for test or main net depends on the environment variables.
Fully Fixes #319
> chore(config): Consolidate Ethereum configs

- apps/server/test-i9n/testing/BridgeContractFixture.ts
- packages/smartcontracts/src/contracts/BridgeV1.sol
- packages/smartcontracts/src/scripts/deployBridgeProxy.ts
- packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.deployment.spec.ts
- packages/smartcontracts/src/tests/testUtils/deployment.ts
- packages/smartcontracts/test-i9n/Bridge.i9n.ts
As per the title, adding the constants to SM.
Easy for backend to fetch this data straight from contract instead of manually updating.
Fixes #345
> feat(Contracts): Added name and version constants to contract

- apps/server/test-i9n/testing/BridgeContractFixture.ts
- packages/smartcontracts/src/contracts/BridgeV1.sol
- packages/smartcontracts/src/scripts/deployBridgeProxy.ts
- packages/smartcontracts/src/scripts/localContractsDeployment.ts
- packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.deployment.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
- packages/smartcontracts/src/tests/testUtils/deployment.ts
- packages/smartcontracts/test-i9n/Bridge.i9n.ts
Implementing the community wallet address where the tx fee will be send upon bridging. 
Both admin and operational addresses will be able to change this address if needed.
#355 
Fixes #355
> feat(SmartContracts): Implement community address

- apps/server/test-i9n/BridgeApp.i9n.ts
- apps/server/test-i9n/defichain/address.i9n.ts
- apps/server/test-i9n/defichain/send.i9n.ts
- apps/server/test-i9n/defichain/stats.i9n.ts
- apps/server/test-i9n/testing/TestingModule.ts
Cleans up code for TestingModule.ts and the various unit and integration tests.
Fixes #347
> fix(code improvements): clean up code

- apps/server/src/ethereum/controllers/EthereumController.ts
- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
- apps/server/src/types/HandledEVMTransaction.ts
- apps/server/test-i9n/ethereum/transactionConfirmer.i9n.ts
Changes the output for /ethereum/handleTransaction route to return number of confirmations and whether the transaction is confirmed.
Fixes #
> feat(EVMTransactionConfirmer): Return number of confirmations for UI

- apps/web/src/components/Banner.tsx
- apps/web/src/components/Header.tsx
Added a top banner to header
Fixes #
> feature(ui-ux): add banner

- apps/server/.env
- apps/server/test-i9n/defichain/containers/DeFiChainStubContainer.ts
> chore(server): updted logic for container mnemonic to use from env variable

- apps/web/src/components/TransactionConfirmationProgressBar.tsx
- apps/web/src/components/TransactionStatus.tsx
> feature(ui-ux): Transaction status progress bar

- apps/web/src/components/TransactionConfirmationProgressBar.tsx
- apps/web/src/components/TransactionStatus.tsx
- apps/web/src/pages/index.tsx
Display transaction confirmation status
Progress bar & circle #417
Fixes #
> feature(ui-ux): transaction status (wip)

- apps/web/src/components/TransactionStatus.tsx
> chore(ui-ux): close transaction button for tablet and mobile

- apps/web/src/hooks/useTransferFee.ts
Adjust the transaction fees: 
EVM -> DFC should be 0.1% wBTC
DFC -> EVM should be 0.3% dBTC
Fixes #
> feature(core): transaction fees adjustment 

- packages/smartcontracts/src/contracts/BridgeV1.sol
- packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.supportedToken.spec.ts
- packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
Add support for ETH as per new requirements
Fixes #401
> chore(smartcontracts): Add support for ETH to smart contracts

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/erc-transfer/StepThreeVerification.tsx
- apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
- apps/web/src/config/networkUrl.ts
- apps/web/src/hooks/useWrappedLazyQuery.ts
- apps/web/src/hooks/useWrappedMutation.ts
- apps/web/src/layouts/Base.tsx
- apps/web/src/store/defichain.tsx
Add dynamic switch to API url based on the current network environment selected.
Fixes #419
> feat(core): Add dynamic server URL

- .github/workflows/release-apps.yml
> chore(workflow): fix release reporting

- apps/web/src/components/ScreenContainer.tsx
- Assume that the bridge is up unless the api explicitly returns isUp !== true
Fixes #
> fix(ui-ux): assume bridge is up unless explicitly returned by api

- apps/server/.env
- apps/server/src/AppModule.ts
- apps/server/src/version/VersionController.ts
- apps/server/src/version/VersionInterface.ts
- apps/server/src/version/VersionModule.ts
- apps/server/test-i9n/testing/VersionService.i9n.ts
Add `/version` api that returns current `APP_VERSION` as defined in `.env`
> feat(core): add Version api

- apps/web/src/components/TransactionStatus.tsx
- apps/web/src/components/commons/ActionButton.tsx
- apps/web/src/constants.ts
- apps/web/src/hooks/useBridgeFormStorageKeys.ts
- apps/web/src/hooks/useWatchEthTxn.ts
- apps/web/src/layouts/contexts/TransactionHashContext.tsx
- apps/web/src/pages/index.tsx
- apps/web/src/store/defichain.tsx
- apps/web/src/store/index.ts
> feat(core): send fund after 65 confirmations

- apps/server/Dockerfile
> chore(workflow): expose port on images build

- apps/web/src/components/erc-transfer/StepThreeVerification.tsx
Fixed for `try - catch` block to enable error catching on verify function on StepThreeVerification.tsx.
Fixes #
> feature(ui-ux): fix verify function not catching error

- apps/web/src/components/BridgeForm.tsx
> fix(ui-ux): fix incorrectly displayed insufficient allowance

- apps/server/test-i9n/defichain/verify.i9n.ts
> chore(test): check that deadline is only set to 24hr

- apps/web/next.config.js
- apps/web/src/config/networkUrl.ts
Map temporary url for testing
Fixes #
> chore(ops): setup temporary domain for remote playground

- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
As titled.
Fixes #
We might need to add new tests on the server side for V2
> feat(server): update bridge proxy to v2

- apps/server/src/AppConfig.ts
- apps/server/src/defichain/controllers/WhaleWalletController.ts
- apps/server/src/defichain/services/WhaleWalletService.ts
- apps/server/src/ethereum/controllers/EthereumController.ts
- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
- apps/server/test-i9n/defichain/balance.i9n.ts
Gets balance of all assets of DFC hotwallet (USDC, USDT, ETH, BTC, DFI). 
Fixes #410
> feat(DFC Balance): added service and integration tests to get asset balance of hotwallet

- apps/server/src/ethereum/controllers/EthereumController.ts
We need to increase throttling limit of `/handleTransaction` api.
Fixes #
We are polling this api every 2 seconds, so that's around 30 requests per minute. Current limit is only set to 10 req per minute so error is often displayed. This is causing more delay to the transaction:
> chore(server): handleTransaction - increase throttle limit

- apps/web/src/components/ConnectButton.tsx
> feat(ui-ux): add transition to connect wallet button

- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> chore(server): log send details

- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
- apps/server/src/utils/TokensUtils.ts
- apps/server/test-i9n/ethereum/allocateDFCFund.i9n.ts
- apps/server/test-i9n/testing/BridgeContractFixture.ts
> fix(server): fixed eth transfer flow for allocate fund

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/MobileBottomMenu.tsx
- apps/web/src/components/WelcomeHeader.tsx
- apps/web/src/components/erc-transfer/StepThreeVerification.tsx
- apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
- apps/web/src/hooks/useSetTimeout.ts
- apps/web/src/pages/index.tsx
- Add url link to Documentation and FAQ
- Add useTimeOut hook
- Add timeout to verify button on DFC > EVM flow when too many request
Fixes #
> feature(ui-ux): add documentation, faq url and add timeout function on DFC > EVM verify function

- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
- apps/server/test-i9n/ethereum/transactionConfirmer.i9n.ts
This PR fixes the /ethereum/balance/{asset} endpoint to return the properly formatted asset balance 
Fixes #487
> fix(evm balance): reworked service to returned appropriate asset dp

- apps/web/src/components/TransactionConfirmationProgressBar.tsx
- apps/web/src/components/TransactionStatus.tsx
- apps/web/src/components/commons/ActionButton.tsx
- apps/web/src/layouts/contexts/TransactionHashContext.tsx
- apps/web/src/pages/index.tsx
- Failed tx - user cannot start a new one, user cannot close
- Failed tx- Disable button when throttle limit is reached (for 1 minute)
- Failed tx- Disable button when api is still loading from retrying
- Improve ui (follow design) except buttons as it requires more refactoring
Fixes #
> chore(ui-ux): handle failed txn

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
> fix(web): added amount validation for small number

- apps/web/src/components/WelcomeHeader.tsx
> fix(ui-ux): hide top faq and documentation in mobile

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/InputSelector.tsx
Add hover state on
1. switch source button show tooltip
2. source network and token with highlighted border
Fixes #
> fix(ui-ux): hover state

- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
As titled.
https://github.com/WavesHQ/bridge/issues/496
Fixes #
> fix(server): prevent negative number of confirmations on

- apps/server/prisma/migrations/20230223061929_v0_1_3/migration.sql
- apps/server/prisma/schema.prisma
- apps/server/src/defichain/services/WhaleWalletService.ts
- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
- apps/server/test-i9n/defichain/address.i9n.ts
- apps/server/test-i9n/defichain/verify.i9n.ts
- apps/server/test-i9n/ethereum/signClaims.i9n.ts
> feature(server): added ability to update mnemonic to manage diff DeFiChainAddressIndex version

- apps/server/prisma/migrations/20230223083837_v0_1_4/migration.sql
- apps/server/prisma/schema.prisma
- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> feat(server): store eth receiver address to DB

- apps/server/src/AppModule.ts
- apps/server/src/balances/BalancesController.ts
- apps/server/src/balances/BalancesInterface.ts
- apps/server/src/balances/BalancesModule.ts
- apps/server/src/balances/BalancesService.ts
- apps/server/src/defichain/DeFiChainModule.ts
- apps/server/test-i9n/balances/balances.i9n.ts
- apps/server/test-i9n/testing/BridgeContractFixture.ts
- apps/server/test-i9n/testing/TestingModule.ts
Add `/balance` api that returns the value of the hot wallets.
example response is
```js
{
"EVM": {
"ETH": "0.19792625446",
"USDT": "10009.9960589",
"WBTC": "53.094803281988",
"USDC": "9991.600398"
},
"DFC": {
"DFI": "0.00000000",
"ETH": "0",
"BTC": "0",
"USDT": "0",
"USDC": "0"
}
}
```
Fixes #494
> feat(core): add /balances api to get wallet balance

- apps/web/cypress/e2e/bridge.spec.ts
- apps/web/src/components/EnvironmentNetworkSwitch.tsx
- apps/web/src/components/WalletAddressInput.tsx
- apps/web/src/config/networkUrl.ts
Fixes #
- Behaviour of the NetworkSwitch button is unchanged, except for unable to switch to Playground
> feat(ui-ux): remove playground env for Testnet testing

- apps/web/src/config/ABIs/mainnet/BridgeV1.json
- apps/web/src/config/ABIs/testnet/BridgeV1.json
> chore(web): update abi to v4

- apps/server/src/BridgeServerApp.ts
- apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> feature(server): restrict cors on prod to allow only quantumbridge.app

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/ConfirmTransferModal.tsx
- apps/web/src/components/WalletAddressInput.tsx
- apps/web/src/types.ts
> chore(ui-ux): updated placeholder text to Eth Address

- apps/web/src/components/WalletAddressInput.tsx
- apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
- apps/web/src/components/erc-transfer/StepOneInitiate.tsx
> chore(ui-ux): improve ui on read only refund address

- .github/workflows/ci.yml
- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/WalletAddressInput.tsx
- apps/web/src/components/erc-transfer/StepOneInitiate.tsx
> chore(ui-ux): fixed modal flicker issue

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/commons/UtilityModal.tsx
To prevent user from accidentally resetting form
Fixes #
> feature(ui-ux): Add confirmation modal upon resetting form

- apps/web/src/components/EnvironmentNetworkSwitch.tsx
- apps/web/src/config/networkUrl.ts
> chore(core): display local playground options when running in local

- apps/web/src/components/WalletAddressInput.tsx
> chore(ui-ux): display wallet address warning on using local playground

- apps/web/src/hooks/useTransferFee.ts
> fix(ui-ux): incorrect transfer fee

- apps/web/src/components/TransactionStatus.tsx
- apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
- apps/web/src/constants.ts
- apps/web/src/hooks/useBridgeFormStorageKeys.ts
- apps/web/src/hooks/useWatchEthTxn.ts
- apps/web/src/layouts/Base.tsx
- apps/web/src/layouts/contexts/DeFiScanContext.tsx
- apps/web/src/layouts/contexts/StorageContext.tsx
- apps/web/src/pages/index.tsx
> feature(ui-ux): show txn hash for defiscan to track the EVM to DFC transfer

- apps/web/src/layouts/contexts/StorageContext.tsx
> fix(ui-ux): fixed txn bug

- apps/web/src/components/Footer.tsx
- apps/web/src/store/defichain.tsx
- apps/web/src/store/index.ts
- apps/web/src/types.ts
- No version number is displayed on the homepage
#545
Fixes #545
> feat(ui-ux): show version number at homepage

- apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
- apps/web/src/components/erc-transfer/StepLastClaim.tsx
> feat(ui-ux): display different message when claim is in progress

- apps/server/src/libs/caches/GlobalCache.ts
- apps/server/src/version/VersionController.ts
- apps/server/src/version/VersionModule.ts
> chore(server): added cache for /version api

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
As titled. More details in the issue attached below.
Fixes #568
> fix(core): web - fix approval loop issue

- apps/web/package.json
- pnpm-lock.yaml
As titled. No need to update anything from our end.
Fixes #534
> chore(ui-ux): bump connectkit version to 1.2.0

- apps/server/prisma/migrations/20230227071459_/migration.sql
- apps/server/prisma/schema.prisma
> chore(ops): add another status for community wallet

- apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
- apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
> fix(ui-ux): eth does not require approval

- apps/server/src/balances/BalancesController.ts
- apps/server/src/defichain/controllers/StatsController.ts
- apps/server/src/defichain/controllers/WhaleWalletController.ts
- Skip throttle for endpoints that does not interact with db
Fixes #
> chore(core): skip throttle

- apps/web/src/components/commons/QuickInputCard.tsx
ETH -> DFC (25%, 50%...(x))
Fixes #
> fix(ui-ux): quick input buttons

- apps/web/src/config/ABIs/mainnet/BridgeV1.json
- apps/web/src/config/ABIs/testnet/BridgeV1.json
As titled. No changes needed in the codebase. Tested that everything is still working fine
Fixes #
> chore(web): update abi

- apps/web/src/config/networkUrl.ts
> chore(api): updated server endpoints for testnet and mainnet

- apps/web/src/components/erc-transfer/DeFiChainToERC20Transfer.tsx
- apps/web/src/styles/globals.scss
- some buttons use this, thanks @fullstackninja864 for pointing it out!
Fixes #
> fix(ui-ux): revert bg-card-section opacity

- apps/web/src/components/commons/QuickInputCard.tsx
- apps/web/src/hooks/useWatchEthTxn.ts
> fix(ui-ux): fix rounding up issue with 6dp

- apps/server/test-i9n/defichain/balance.i9n.ts
- apps/server/test-i9n/ethereum/signClaims.i9n.ts
- apps/web/src/components/TransactionStatus.tsx
> chore(ui-ux): updated txn status and updated test case

- apps/web/src/config/ABIs/mainnet/BridgeV1.json
- apps/web/src/config/ABIs/testnet/BridgeV1.json
> chore(web): update client ABI to latest v5 version

- apps/server/src/BridgeServerApp.ts
- apps/server/src/defichain/services/WhaleWalletService.ts
- apps/server/test-i9n/defichain/verify.i9n.ts
In order to log the entire stack trace for `HttpException` we are throwing. As [mentioned](https://github.com/iamolegga/nestjs-pino#expose-stack-trace-and-error-class-in-err-property) on the docs.
Fixes #
> chore(server): improve logged error details

- apps/web/src/components/commons/QuickInputCard.tsx
Apologize the previous fix not correct
Fixes #
> fix(uix-ux): fix the rounding on number input

- apps/web/cypress/e2e/bridge.spec.ts
- apps/web/cypress/e2e/index.spec.ts
- apps/web/cypress/e2e/maintenance.spec.ts
- apps/web/src/components/Maintenance.tsx
- apps/web/src/components/ScreenContainer.tsx
- apps/web/src/store/defichain.tsx
- apps/web/src/types.ts
> fix(ui-ux): fixed flicker issue for maintenance page

- apps/web/next.config.js
- apps/web/src/config/networkUrl.ts
> chore(web): update network url for staging and prod

- packages/smartcontracts/src/contracts/test/TestToken.sol
- packages/smartcontracts/src/scripts/deployBridgeImplementation.ts
- packages/smartcontracts/src/scripts/deployBridgeProxy.ts
- packages/smartcontracts/src/scripts/deployTimelockController.ts
- packages/smartcontracts/src/scripts/mainnetContractsDeployment.ts
- packages/smartcontracts/src/scripts/utils/verify.ts
Introduce the script that verify the SMs after the deployment, Instead of doing it manually
Fixes #
> feat(Contracts): Added script to verify contracts after the deployment

- apps/web/src/components/ConfirmTransferModal.tsx
> fix(core): fix incorrect claim amount

- apps/web/src/components/BridgeForm.tsx
> fix(ui-ux): hide balance error if there is pending txn

- apps/web/src/components/QrAddress.tsx
- apps/web/src/components/erc-transfer/StepThreeVerification.tsx
> fix(ui-ux): fix stucked success copy message

- apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
- apps/web/src/hooks/useWriteApproveToken.ts
- apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
- as titled
Fixes #647
- This will not open metamask in case the approving of token for eth is called
> fix(ui-ux): avoid approving eth

- apps/server/prisma/migrations/20230306055552_v0_1_0/migration.sql
- apps/server/prisma/schema.prisma
- apps/server/src/defichain/model/VerifyDto.ts
- apps/server/src/defichain/services/WhaleWalletService.ts
- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
- apps/server/test-i9n/ethereum/signClaims.i9n.ts
> chore(server): save claimable amount and token symbol to db

- apps/server/src/CustomErrorCodes.ts
- apps/server/src/defichain/services/WhaleWalletService.ts
- apps/server/test-i9n/defichain/verify.i9n.ts
- apps/server/test-i9n/testing/TestingModule.ts
Throws error while unsupported token is passed to /verify api
Fixes #638
> chore(api): check supported tokens in verify api

- apps/server/src/settings/SettingsController.ts
- apps/server/src/settings/SettingsInterface.ts
- apps/server/test-i9n/testing/SettingsController.i9n.ts
- apps/server/test-i9n/testing/TestingModule.ts
- apps/web/src/types.ts
> chore(server): return network to `/settings` api and add tests

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/commons/ActionButton.tsx
- apps/web/src/components/commons/ErrorModal.tsx
- apps/web/src/components/commons/UtilityModal.tsx
- apps/web/src/components/erc-transfer/RestoreTransactionModal.tsx
This PR contain
1. Aligned X and Close buttons in Transaction error modal 
2. Minor UI fixes
Fixes #608
> fix(ui-ux): aligned X and Close buttons in Transaction error modal

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/ConnectButton.tsx
- apps/web/src/components/EnvironmentNetworkSwitch.tsx
- apps/web/src/components/WalletAddressInput.tsx
- apps/web/src/config/ABIs/mainnet/BridgeV1.json
- apps/web/src/config/index.ts
- apps/web/src/layouts/Base.tsx
- apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
> chore(mainnet): prepare mainnet display [Merge when ready to go on MainNet]

- apps/web/next.config.js
> chore(ui-ux): add mainnet.infura domain to CSP

- apps/web/src/components/WelcomeHeader.tsx
> chore(ui-ux): change to american english

- apps/web/src/layouts/Base.tsx
> chore(core): use infura url for mainnet

- .github/renovate.json
- .github/workflows/ci-db-staging.yml
- .github/workflows/ci.yml
- .npmrc
- apps/server/Dockerfile
- apps/server/package.json
- package.json
- pnpm-lock.yaml
> chore(ops): update pnpm

- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/erc-transfer/StepLastClaim.tsx
- apps/web/src/hooks/useCheckBalance.ts
- apps/web/src/layouts/contexts/NetworkContext.tsx
> fix(ui-ux): prevent user from bridging when token is unsupported

- .npmrc
- apps/web/src/components/siteInfo.ts
https://github.com/iamvishnusankar/next-sitemap#building-sitemaps-with-pnpm
Fixes #
> chore(ops): update missing npm config to generate sitemaps

- apps/web/src/components/ScreenContainer.tsx
> fix(ui-ux): footer position and screen height

- apps/server/src/CustomErrorCodes.ts
update `TokenSymbolNotSupported` error code to 6 to match with [documentations](https://birthdayresearch.notion.site/Error-Codes-d5c0bfd68359466e88223791e69adb4f)
Fixes #
> fix(api): update error codes

- apps/server/src/utils/TokensUtils.ts
- apps/web/src/config/index.ts
- apps/web/src/layouts/contexts/NetworkContext.tsx
- apps/web/src/types.ts
> fix(server): update wbtc mapping

- apps/server/src/defichain/services/WhaleWalletService.ts
- apps/server/test-i9n/defichain/verify.i9n.ts
- apps/web/src/components/BridgeForm.tsx
- apps/web/src/components/commons/QuickInputCard.tsx
- apps/web/src/components/erc-transfer/StepThreeVerification.tsx
> fix(ui-ux): change to 5dp 

- apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
- apps/web/src/hooks/useWriteBridgeToDeFiChain.ts
> fix(core): fix allowance error on mainnet

- apps/server/package.json
- apps/server/src/BridgeServerApp.ts
- apps/server/src/modules/BaseModule.ts
- apps/server/src/settings/SettingsController.ts
- apps/web/next.config.js
- apps/web/src/layouts/Base.tsx
- pnpm-lock.yaml
1. Add raygun for error handling
2. Add compression for server
Fixes #
> feature(web): add raygun and compression

- apps/web/src/components/ConfirmTransferModal.tsx
- apps/web/src/components/erc-transfer/EvmToDeFiChainTransfer.tsx
- apps/web/src/hooks/useWriteApproveToken.ts
> chore(core): evm to dfc - remove polling of token data

- apps/web/src/components/WalletAddressInput.tsx
- apps/web/src/components/icons/MetaMaskIconSmall.tsx
Fixes https://github.com/WavesHQ/quantum/issues/700
> chore(ui-ux): add use address 

- apps/server/src/version/VersionController.ts
> chore(server): skip throttle for /version

- apps/web/src/components/BridgeForm.tsx
> fix(ui-ux): fetch balance on eth token

- apps/web/src/components/erc-transfer/StepLastClaim.tsx
> fix(core): fix claimfund race condition issue

- apps/web/src/components/erc-transfer/StepLastClaim.tsx
> fix(claim): fix claim error

- apps/web/src/components/Footer.tsx
- apps/web/src/components/commons/Socials.tsx
> fix(ui-ux): fixed ui alignments

- apps/web/src/components/Footer.tsx
- apps/web/src/hooks/useWrappedQuery.ts
- apps/web/src/layouts/Base.tsx
- apps/web/src/store/defichain.tsx
- apps/web/src/store/index.ts
- apps/web/src/store/reducers/rootReducer.ts
- apps/web/src/store/slices/versionSlice.ts
- apps/web/src/store/store.ts
add `app-version` header to all API calls to server. Default value is set as `0.0.0`.
Fixes #694
> feat(core): add app-version header to all api calls

- apps/web/src/pages/index.tsx
> chore(ui-ux): update bridge maintenance status condition

- apps/web/cypress/e2e/maintenance.spec.ts
- apps/web/src/components/ScreenContainer.tsx
> fix(ui-ux): fixed error 404 redirects to incorrect UI

- apps/web/cypress/e2e/bridge.spec.ts
- apps/web/cypress/e2e/index.spec.ts
- apps/web/cypress/e2e/maintenance.spec.ts
Tests are not using local APIs, so it fails when the Ocean api is down
Fixes #
> fix(e2e): always target local api for tests

- apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
> chore(ui-ux): set default network to TestNet on Goerli

- apps/web/next.config.js
- apps/web/src/config/networkUrl.ts
> chore(core): use new api endpoint

- apps/web/next.config.js
- apps/web/src/config/networkUrl.ts
> chore(web): update testnet network url

- apps/server/test-i9n/balances/balances.i9n.ts
- apps/server/test-i9n/defichain/balance.i9n.ts
> chore(e2e): enabled EUROC testcase

- .github/CODEOWNERS
As per title. Removing certain codeowners since the manpower has shifted focus to other areas.
Fixes #
> chore(github): Remove certain codeowners

- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/ISSUE_TEMPLATE/2-enhancement.md
- .github/ISSUE_TEMPLATE/3-general.md
- .github/ISSUE_TEMPLATE/4-ui-ux-improvements.md
- .github/ISSUE_TEMPLATE/5-translation-improvements.md
…e(s)
Update typo(s) from "DeFiChain Wallet" to "Quantum" for all issue templates
Fixes #
> chore(docs): update issue templates

- apps/server/src/defichain/services/WhaleWalletService.ts
- apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> chore(logs): add error logs

- .github/workflows/ci-db-staging.yml
- .github/workflows/ci-e2e.yml
- .github/workflows/ci.yml
- package.json
Update `pnpm` version to `7.29.3` to fix issue with node deps not being installed.
> fix(deps): update pnpm version in CI

- .github/ISSUE_TEMPLATE/4-ui-ux-improvements.md
Update typo(s) from "DQuantum" to "Quantum" for ui-ux Improvements Template
Fixes #
> chore(docs): update issue templates; uiuxImprovements

- README.md
- packages/smartcontracts/README.md
> Fix: typos

- apps/web/src/layouts/contexts/NetworkContext.tsx
> chore(ops): enable DFI on client
